# NumPy
Numpy is the core library for scientific computing in Python. <br/>
It provides a high-performance multidimensional array object, and tools for working with these arrays. <br/>
Official NumPy Documentation: https://numpy.org/doc/stable/reference/ 

In [ ]:
# Install NumPy 
# ! pip install numpy

Since NumPy is not a default thing in Python. We import this library. When we import a library we allow all the functions and types with the initial of that library.

In [1]:
# Import NumPy
import numpy as np

# NumPy Arrays
A grid of values, all of the same type. <br/>
**Rank:** number of dimensions of the array <br/>
**Shape:** an array of tuple of integers giving the size of the array along each dimension.

In [2]:
# Rank 1 array
a = np.array([1, 2, 3])   
print(type(a))            # Prints data type

<class 'numpy.ndarray'>


In [3]:
print(a.shape)

(3,)


In [4]:
print(a[0], a[1], a[2])   # Indexing         

1 2 3


In [5]:
a[0] = 5                  # Assigning
print(a) 

[5 2 3]


In [6]:
# Rank 2 array
b = np.array([ [1,2,3], [4,5,6]  ])
'''
# of elements in first 3rd bracket => 2
# of elements in second 3rd bracket => 3
'''

print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0], b[1,2])

(2, 3)
1 2 4 6


## Special Arrays

In [9]:
a = np.zeros((2,6))   # Create an array of all zeros
a            

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
b = np.array([ [1,2,3], [4,5,6]  ])
np.zeros_like(b,dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
b = np.ones((3,2))    # Create an array of all ones
b             

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
c = np.full((2,4), 7)  # Create a constant array
c             

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [18]:
d = np.eye(3)         # Create a nxn identity matrix
d           

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
e = np.random.random((4,3))  # Create an array filled with random values
e

array([[0.94195354, 0.6508818 , 0.38246379],
       [0.1478197 , 0.70258884, 0.62082502],
       [0.71498787, 0.07186978, 0.79179048],
       [0.91398124, 0.17733808, 0.09969283]])

## Indexing

In [24]:
a = np.array([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12],
              [1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
a[:4,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [ 1,  2,  3]])

In [29]:
b = a[:4,1:3]
b

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [ 2,  3]])

In [30]:
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [38]:
a[1, :], a[1, :].shape

(array([5, 6, 7, 8]), (4,))

In [39]:
a[1:2, :], a[1:2, :].shape

(array([[5, 6, 7, 8]]), (1, 4))

In [42]:
a[:, 1], a[:, 1].shape

(array([77,  6, 10,  2,  6, 10]), (6,))

In [43]:
a[:, 1:2], a[:, 1:2].shape

(array([[77],
        [ 6],
        [10],
        [ 2],
        [ 6],
        [10]]), (6, 1))

In [44]:
np.arange(2,10,2) # (start, end+1, step)

array([2, 4, 6, 8])

## Boolean array indexing

In [45]:
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
bool_idx = (a>10)
bool_idx

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [47]:
a[bool_idx]

array([77, 11, 12, 11, 12])

In [49]:
a [ a>10 ]

array([77, 11, 12, 11, 12])

# Data Types

In [50]:
x = np.array([1, 2])   
print(x.dtype)         

int64


In [52]:
x = np.array([1.0, 2.0])
print(x.dtype)

float64


In [53]:
x = np.array([1, 2], dtype=np.float64) # Forcing a particular datatype
print(x,x.dtype) 

[1. 2.] float64


In [54]:
x.dtype

dtype('float64')

# Operations

In [56]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [57]:
# Adding two arrays element-wise
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [58]:
# Substracting two arrays element-wise
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [59]:
# Mutiplication Element-wise
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [60]:
# Elementwise division
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [61]:
# Elementwise square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [62]:
# Matrix Multiplication
print(x.dot(y))
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [63]:
x

array([[1., 2.],
       [3., 4.]])

In [64]:
# Sum of all elements in the array
np.sum(x)

10.0

In [65]:
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1))  # Compute sum of each row

[4. 6.]
[3. 7.]


In [69]:
a, a.shape

(array([[ 1, 77,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), (6, 4))

In [70]:
# Transpose
a.T, a.T.shape

(array([[ 1,  5,  9,  1,  5,  9],
        [77,  6, 10,  2,  6, 10],
        [ 3,  7, 11,  3,  7, 11],
        [ 4,  8, 12,  4,  8, 12]]), (4, 6))

# Broadcasting

In [71]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [72]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([4,5])
(x.T+y).T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [76]:
x, x.shape

(array([[1, 2, 3],
        [4, 5, 6]]), (2, 3))

In [77]:
x.T, x.T.shape

(array([[1, 4],
        [2, 5],
        [3, 6]]), (3, 2))

In [78]:
y, y.shape

(array([4, 5]), (2,))

In [79]:
x.T+y

array([[ 5,  9],
       [ 6, 10],
       [ 7, 11]])

In [80]:
(x.T+y).T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [81]:
x*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [82]:
x+2

array([[3, 4, 5],
       [6, 7, 8]])