# What is PyTorch
- PyTorch is an open-source machine learning library for Python, primarily developed by Meta (previously Facebook) AI Research lab.

- It is known for its ease of use, dynamic computational graphs, and support for a wide range of hardware platforms. 

- PyTorch provides a high-level interface for working with neural networks and other machine learning models, and it allows for easy integration with other popular Python libraries and frameworks. 

- It also has a large and active community of developers and users, making it a popular choice for building and deploying machine learning models.

In [2]:
import torch

# What is Tensor
- In PyTorch, a tensor is a multi-dimensional array similar to a NumPy array, but with the added capability to run on GPUs for faster computation. 
- Tensors in PyTorch are similar to ndarrays in NumPy, with the addition of support for GPU acceleration and automatic differentiation that are crucial for building and training neural networks. 
- They can be used to store a variety of data types, including integers, floating point numbers, and Boolean values. 
- Tensors are the fundamental building blocks of neural networks and other machine learning models in PyTorch, and they are used to represent the inputs, outputs, and parameters of the model. 
- Pytorch provides a wide range of tensor operations, including mathematical operations, indexing, slicing, reshaping, and many more. 

In [3]:
from torch import tensor

In [4]:
a = tensor([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
      ]
    )
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
a.size(), a.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

In [6]:
a[0,0], a[0,1], a[1,0], a[1,2]

(tensor(1), tensor(2), tensor(4), tensor(6))

## Special Arrays

In [7]:
a = torch.zeros((2,6))   # Create a tensor array of all zeros
a            

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [8]:
b = torch.tensor([ [1,2,3], [4,5,6]  ])
torch.zeros_like(b,dtype=int)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [9]:
b = torch.ones((3,2))    # Create a tensor array of all ones
b   

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [10]:
c = torch.full((2,4), 7)  # Create a constant tensor array
c   

tensor([[7, 7, 7, 7],
        [7, 7, 7, 7]])

In [11]:
d = torch.eye(3)         # Create a nxn identity matrix with tensors
d  

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
e = torch.randn((4,3))  # Create a tensor array filled with random values
e

tensor([[ 1.0806,  0.4663, -0.4731],
        [ 0.0472,  1.1504,  2.0735],
        [-0.5988,  2.1212,  1.6686],
        [-0.7932,  3.0033, -0.9890]])

## Indexing

In [23]:
a = tensor([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12],
              [1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]])
a

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [14]:
a[:4,:3]

tensor([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [ 1,  2,  3]])

In [15]:
b = a[:4,1:3]
b

tensor([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [ 2,  3]])

In [16]:
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

tensor(2)
tensor(77)


In [25]:
b = a
c = a.clone()
c[0,0] = 100
b[0,1] = 8
a

tensor([[ 1,  8,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [26]:
a[1, :], a[1, :].shape

(tensor([5, 6, 7, 8]), torch.Size([4]))

In [27]:
a[1:2, :], a[1:2, :].shape

(tensor([[5, 6, 7, 8]]), torch.Size([1, 4]))

In [28]:
a[:, 1], a[:, 1].shape

(tensor([ 8,  6, 10,  2,  6, 10]), torch.Size([6]))

In [29]:
a[:, 1:2], a[:, 1:2].shape

(tensor([[ 8],
         [ 6],
         [10],
         [ 2],
         [ 6],
         [10]]), torch.Size([6, 1]))

In [30]:
torch.arange(2,10,2) # (start, end+1, step)

tensor([2, 4, 6, 8])

In [31]:
torch.linspace(2,10,2) # (start, end, number_of_samples)

tensor([ 2., 10.])

In [32]:
torch.linspace(2,10,7) # (start, end, number_of_samples)

tensor([ 2.0000,  3.3333,  4.6667,  6.0000,  7.3333,  8.6667, 10.0000])

## Boolean array indexing

In [33]:
a

tensor([[ 1,  8,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [34]:
bool_idx = (a>10)
bool_idx

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False,  True,  True],
        [False, False, False, False],
        [False, False, False, False],
        [False, False,  True,  True]])

In [35]:
a[bool_idx]

tensor([11, 12, 11, 12])

In [36]:
a [ a>10 ]

tensor([11, 12, 11, 12])

# Data Types

In [37]:
x = tensor([1, 2])   
print(x.dtype) 

torch.int64


In [38]:
x = tensor([1.0, 2.0])
print(x.dtype)

torch.float32


In [39]:
x = tensor([1, 2], dtype=torch.float64) # Forcing a particular datatype
x, x.dtype 

(tensor([1., 2.], dtype=torch.float64), torch.float64)

In [40]:
x = tensor([1, 2])   
x.type()

'torch.LongTensor'

In [41]:
x = tensor([1.0, 2.0])
x.type()

'torch.FloatTensor'

In [42]:
x = tensor([1, 2], dtype=torch.float64)
x.type()

'torch.DoubleTensor'

# Operations

In [43]:
x = tensor([[1,2],[3,4]], dtype=torch.float64)
y = tensor([[5,6],[7,8]], dtype=torch.float64)

print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([[5., 6.],
        [7., 8.]], dtype=torch.float64)


In [44]:
print(x + y)
print(torch.add(x, y))

tensor([[ 6.,  8.],
        [10., 12.]], dtype=torch.float64)
tensor([[ 6.,  8.],
        [10., 12.]], dtype=torch.float64)


In [45]:
print(x - y)
print(torch.subtract(x, y))

tensor([[-4., -4.],
        [-4., -4.]], dtype=torch.float64)
tensor([[-4., -4.],
        [-4., -4.]], dtype=torch.float64)


In [46]:
print(x * y)
print(torch.multiply(x, y))

tensor([[ 5., 12.],
        [21., 32.]], dtype=torch.float64)
tensor([[ 5., 12.],
        [21., 32.]], dtype=torch.float64)


In [47]:
print(x / y)
print(torch.divide(x, y))

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]], dtype=torch.float64)
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]], dtype=torch.float64)


In [48]:
print(torch.sqrt(x))

tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]], dtype=torch.float64)


In [51]:
a = tensor([1,2])
b = tensor([2,1])
torch.dot(a,b)

tensor(4)

In [52]:
print(torch.matmul(x, y))

tensor([[19., 22.],
        [43., 50.]], dtype=torch.float64)


In [53]:
torch.sum(x)

tensor(10., dtype=torch.float64)

In [54]:
print(torch.sum(x, axis=0))  # Compute sum of each column
print(torch.sum(x, axis=1))  # Compute sum of each row

tensor([4., 6.], dtype=torch.float64)
tensor([3., 7.], dtype=torch.float64)


In [55]:
a, a.shape

(tensor([1, 2]), torch.Size([2]))

In [56]:
# Transpose
a.T, a.T.shape

<ipython-input-56-8838559511b9>:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3277.)
  a.T, a.T.shape


(tensor([1, 2]), torch.Size([2]))

In [57]:
# Concatenation [similar to np.concatenate]
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = torch.cat([x, y], dim=0)
print(z)

tensor([[ 3.1776,  0.8125,  1.2969],
        [ 0.9024, -0.0380, -1.3395],
        [-0.6104,  0.8617,  1.7753],
        [-0.4712,  0.0439,  0.5325]])


In [58]:
# Concatenation [similar to np.concatenate]
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = torch.cat([x, y], dim=1)
print(z)

tensor([[ 1.0116, -0.0587,  0.5515, -1.9536,  2.2455,  0.4320],
        [ 0.0909,  1.0102,  0.2072,  0.7004, -0.3936,  0.5708]])


In [59]:
# Stacking [Warning: stacking and concatenation is not same]
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = torch.stack([x, y], dim=0)
print(z)

tensor([[[ 0.7257,  0.0053,  1.8921],
         [ 1.4681,  0.1113,  0.0303]],

        [[-0.2803,  0.9583,  0.6434],
         [ 0.1852, -2.3153, -0.4052]]])


In [60]:
# Convert data type
x = tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
x.float()

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [61]:
x = torch.randn(2, 3)
print(x)
print(x.int())

tensor([[-1.0807,  0.6185, -0.8845],
        [ 0.0631, -0.0702, -0.0426]])
tensor([[-1,  0,  0],
        [ 0,  0,  0]], dtype=torch.int32)


# Broadcasting

In [62]:
x = tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = tensor([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


In [63]:
x = tensor([[1,2,3], [4,5,6]])
y = tensor([4,5])
(x.T+y).T

tensor([[ 5,  6,  7],
        [ 9, 10, 11]])

In [64]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [65]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])